
window.alert('Bem vindo!');
//  Posso deixar sem a palavra window também...

window.confirm('Está gostando de programação?');
// Os programas são executados comforme a ordem, ou seja de cima para baixo...
window.prompt('Qual é seu nome?')
// Ocomando acima PROMPT é para a pesssoa colocar seu nome...
